### ISSUE TITLE
Bouton d'ajout de dés

### ISSUE THREAD

**Issue by Lostmindy** [gp-kim/Blank-Theme#1]
Hello ! 

Comme je suis sur une commande qui touche au template posting_body et ses collègues, j'ai découvert un petit souci au niveau du système de lancers de dés. 

Dans le template posting_body l'affichage du petit "+" servant à rajouter un dé à lancer semble non fonctionnel. 

D'après le code, cela correspond à cette partie dans le code (deux fois, une fois dans le JS de l'ajout d'un dé, et une fois dans le HTML)
```js
<img src="{PATH_IMG_FA}tabs_more.gif" alt="plus" />
```

Ce qui, pour une raison qui m'échappe, potentiellement un JS natif de FA, est remplacé à l'affichage par ce code : 
```html
<img class="sprite-tabs_more" src="https://2img.net/i/empty.gif" alt="plus">
```

Donc dans la version qui s'affiche en fin de parcours, FA utilise un sprite via la classe `sprite-tabs_more`, ce qui fait qu'avec le CSS du Blank Theme qui remplace le CSS de base de FA, ce symbole ne s'affiche plus. Ma solution a été juste de remplacer l'image par un bête "+".

Voilà voilà !

**Comment by Lostmindy** [comment]
Wait, d'où vient ta version du code ? C'est le code d'origine de FA ? Mais du coup pourquoi même avec la version du blank theme qui ne contient pas cette partie avec le `sprite-tabs_more` il apparait quand même et remplace l'image inexistante ? Qu'est-ce que FA a encore fumé ?

**Comment by caezd** [comment]
Le bloc de code provient du template de base de ModernBB, dans celui du Blank Thème la classe A été retirée.

Mais de base, cette ligne là `<img src="{PATH_IMG_FA}tabs_more.gif" alt="plus" />` n'est jamais utilisée, donc les images hébergée sur le forum ne sont même pas liées à cette icône (si jamais on changerait le petit + fourni de base ça ne modifierait pas celui là, et plein d'autres icônes d'ailleurs qui sont gérées grâce à des classes qui commencent toutes par `.sprite-`.

C'est très étrange, dans tous les cas 🤦

**Comment by gp-kim** [comment]
Je sais pas pourquoi je continue d'être surprise par ce genre de cas haha 💀

J'ai opté pour ta solution @Lostmindy et juste de remplacer l'image par un petit `+` !

Merci tout les deux d'avoir pris le temps de regarder ça de plus près <3
